/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudyRouteImport } from './routes/study'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as ConvertRouteImport } from './routes/convert'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReadBookIdRouteImport } from './routes/read.$bookId'
import { Route as GuidesGuideIdRouteImport } from './routes/guides.$guideId'
import { Route as CharactersCharRouteImport } from './routes/characters.$char'
import { Route as BooksBookIdRouteImport } from './routes/books.$bookId'

const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvertRoute = ConvertRouteImport.update({
  id: '/convert',
  path: '/convert',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadBookIdRoute = ReadBookIdRouteImport.update({
  id: '/read/$bookId',
  path: '/read/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesGuideIdRoute = GuidesGuideIdRouteImport.update({
  id: '/guides/$guideId',
  path: '/guides/$guideId',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersCharRoute = CharactersCharRouteImport.update({
  id: '/characters/$char',
  path: '/characters/$char',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/convert': typeof ConvertRoute
  '/discover': typeof DiscoverRoute
  '/study': typeof StudyRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/characters/$char': typeof CharactersCharRoute
  '/guides/$guideId': typeof GuidesGuideIdRoute
  '/read/$bookId': typeof ReadBookIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/convert': typeof ConvertRoute
  '/discover': typeof DiscoverRoute
  '/study': typeof StudyRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/characters/$char': typeof CharactersCharRoute
  '/guides/$guideId': typeof GuidesGuideIdRoute
  '/read/$bookId': typeof ReadBookIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/convert': typeof ConvertRoute
  '/discover': typeof DiscoverRoute
  '/study': typeof StudyRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/characters/$char': typeof CharactersCharRoute
  '/guides/$guideId': typeof GuidesGuideIdRoute
  '/read/$bookId': typeof ReadBookIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/convert'
    | '/discover'
    | '/study'
    | '/books/$bookId'
    | '/characters/$char'
    | '/guides/$guideId'
    | '/read/$bookId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/convert'
    | '/discover'
    | '/study'
    | '/books/$bookId'
    | '/characters/$char'
    | '/guides/$guideId'
    | '/read/$bookId'
  id:
    | '__root__'
    | '/'
    | '/convert'
    | '/discover'
    | '/study'
    | '/books/$bookId'
    | '/characters/$char'
    | '/guides/$guideId'
    | '/read/$bookId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConvertRoute: typeof ConvertRoute
  DiscoverRoute: typeof DiscoverRoute
  StudyRoute: typeof StudyRoute
  BooksBookIdRoute: typeof BooksBookIdRoute
  CharactersCharRoute: typeof CharactersCharRoute
  GuidesGuideIdRoute: typeof GuidesGuideIdRoute
  ReadBookIdRoute: typeof ReadBookIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convert': {
      id: '/convert'
      path: '/convert'
      fullPath: '/convert'
      preLoaderRoute: typeof ConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$bookId': {
      id: '/read/$bookId'
      path: '/read/$bookId'
      fullPath: '/read/$bookId'
      preLoaderRoute: typeof ReadBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$guideId': {
      id: '/guides/$guideId'
      path: '/guides/$guideId'
      fullPath: '/guides/$guideId'
      preLoaderRoute: typeof GuidesGuideIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/$char': {
      id: '/characters/$char'
      path: '/characters/$char'
      fullPath: '/characters/$char'
      preLoaderRoute: typeof CharactersCharRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConvertRoute: ConvertRoute,
  DiscoverRoute: DiscoverRoute,
  StudyRoute: StudyRoute,
  BooksBookIdRoute: BooksBookIdRoute,
  CharactersCharRoute: CharactersCharRoute,
  GuidesGuideIdRoute: GuidesGuideIdRoute,
  ReadBookIdRoute: ReadBookIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
